#define REF(A, B) (scm_c_public_ref(A, B))
#define FROM_P(P) (scm_from_pointer(P, NULL))
#define TO_P(P) (scm_to_pointer(P))
#define REF_CALL_1(M, N, ARG1) (scm_call_1(REF(M, N), ARG1))
#define REF_CALL_2(M, N, ARG1, ARG2) (scm_call_2(REF(M, N), ARG1, ARG2))
#define REF_CALL_3(M, N, ARG1, ARG2 ,ARG3) (scm_call_3(REF(M, N), ARG1, ARG2,ARG3))
#define SCM_LOOKUP_REF(name)    (scm_variable_ref(scm_c_lookup(name)))
#define WRAP_WLR_BACKEND(p) (REF_CALL_1("wlroots backend", "wrap-wlr-backend",FROM_P(p)))
#define UNWRAP_WLR_BACKEND(p) (TO_P(REF_CALL_1("wlroots backend", "unwrap-wlr-backend",p)))
#define WRAP_WLR_XDG_SHELL(p) (REF_CALL_1("wlroots types xdg-shell", "wrap-wlr-xdg-shell",FROM_P(p)))
#define UNWRAP_WLR_XDG_SHELL(p) (TO_P(REF_CALL_1("wlroots types xdg-shell", "unwrap-wlr-xdg-shell",p)))
#define WRAP_WLR_XDG_SURFACE(p) (REF_CALL_1("wlroots types xdg-shell", "wrap-wlr-xdg-surface",FROM_P(p)))
#define UNWRAP_WLR_XDG_SURFACE(p) (TO_P(REF_CALL_1("wlroots types xdg-shell", "unwrap-wlr-xdg-surface",p)))
#define WRAP_WLR_XDG_TOPLEVEL(p) (REF_CALL_1("wlroots types xdg-shell", "wrap-wlr-xdg-toplevel",FROM_P(p)))
#define UNWRAP_WLR_XDG_TOPLEVEL(p) (TO_P(REF_CALL_1("wlroots types xdg-shell", "unwrap-wlr-xdg-toplevel",p)))
#define WRAP_WLR_OUTPUT(p) (REF_CALL_1("wlroots types output", "wrap-wlr-output",FROM_P(p)))
#define UNWRAP_WLR_OUTPUT(p) (TO_P(REF_CALL_1("wlroots types output", "unwrap-wlr-output",p)))
